trigger:
  - master
variables:
  - group: DEV

stages:
  - stage: Build
    displayName: Build Package
    pool: $(AGENTS)
    jobs: 
    - job: BuildPackage
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            write-Host "Artifact staging directory is: $(Build.ArtifactStagingDirectory)"
      - task: DeleteFiles@1
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)'
          Contents: '**/drop/*'
      - task: UiPathPack@2
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'UIPath Orchestrator'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop
    - job: BuildTestProject
      steps:
      - task: DeleteFiles@1
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)'
          Contents: '**/tests/*'
      - task: UiPathPack@2
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Tests'
          orchestratorConnection: 'UIPath Orchestrator'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: tests

  - stage: Assest
    displayName: Create Assests
    pool: $(AGENTS)
    jobs:
      - job: CreateAssests
        steps:
        - task: UiPathAssets@2
          inputs:
            orchestratorConnection: 'UIPath Orchestrator'
            folderName: 'Shared'
            assetActionType: 'Deploy'
            csvFile: '$(Build.SourcesDirectory)\Data\Assests.csv'

  - stage: DeployDEV
    pool: $(AGENTS)
    displayName: Deploy build artifact to DEV
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to DEV Orchestrator
        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: 'UIPath Orchestrator'
                packagesPath: '$(Pipeline.Workspace)\drop\'
                folderName: 'Shared'
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: 'UIPath Orchestrator'
                packagesPath: '$(Pipeline.Workspace)\tests\'
                folderName: 'Shared/TestCases'
                entryPoints: TestCase.xaml
                
#  - stage: TestDEV
#    displayName:  Test After Publish
#    dependsOn: DeployDEV
#    condition: succeeded()
#    pool: $(AGENTS)
#    jobs:
#      - job: TestDEV
#        steps:
#          - task: UiPathTest@2
#            inputs:
#              testTarget: 'TestSet'
#              orchestratorConnection: 'UIPath Orchestrator'
#              testSet: 'UiPathAzureDevOps_Tests'
#              folderName: 'Shared'
#              testReportDestination: '$(Pipeline.Workspace)\tests\'

  - stage: TestExec
    displayName:  Test Case Execution
    dependsOn: DeployDEV
    condition: succeeded()
    pool: $(AGENTS)
    jobs:
      - job: TestExec
        steps:
          - task: UiPathTest@2
            inputs:
              testTarget: 'TestProject'
              orchestratorConnection: 'UIPath Orchestrator'
              folderName: 'Shared/TestCases'
              testReportDestination: '$(Pipeline.Workspace)\tests\'
              traceLevel: 'Information'
              timeout: 180

